Controllers/DetailsMonitorController.cs
using EMarket.Data.Interfaces;
using EMarket.Data.Models;
using EMarket.ViewModel;
using Microsoft.AspNetCore.Mvc;

namespace EMarket.Controllers
{
    public class DetailsMonitorController : Controller
    {        
        private readonly IAllMonitors MonitorRep;        
               
        public DetailsMonitorController(IAllMonitors monitorRep)
        {
            MonitorRep = monitorRep;            
        }       

        [HttpGet]
        public ActionResult OpenInfo(int id)
        {
            Monitor monitor = MonitorRep.GetObjectMonitor(id);
            var detailsMonitor = new DetailsMonitorViewModel { DetailsMonitor = monitor };
            return View(detailsMonitor);            
        }
    }
}

Controllers/MonitorsController.cs
using EMarket.Data.Interfaces;
using EMarket.Data.Models;
using EMarket.ViewModel;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Linq.Dynamic.Core;

namespace EMarket.Controllers
{
    public class MonitorsController : Controller
    {
        private readonly IAllMonitors AllMonitors;
        private readonly IMonitorsCategory MonitorsCategory;
        private readonly IAllFilters MonitorsFilters;
        List<Monitor> tempListCategory = new List<Monitor>();
        List<Monitor> tempListColor = new List<Monitor>();
        List<Monitor> tempListDiagonal = new List<Monitor>();
        int checkedEmptyList = 0;

        public MonitorsController(IAllMonitors allMonitors, IMonitorsCategory monitorsCategory, IAllFilters monitorFilters)
        {
            AllMonitors = allMonitors;
            MonitorsCategory = monitorsCategory;
            MonitorsFilters = monitorFilters;
        }

        [HttpGet]
        [Route("Monitors/List")]
        [Route("Monitors/List/{category}")]
        public IActionResult List(string searchString, string category)
        {
            ViewBag.Title = "iiayma monitors";
            IEnumerable<Monitor> monitors = AllMonitors.Monitors;
            IList<Category> categoryList = MonitorsCategory.AllCategory.ToList();
            IList <Filter> filterListDiagonal = MonitorsFilters.AllFilterDiagonal.ToList();
            IList <Filter> filterListColor = MonitorsFilters.AllFilterColor.ToList();
            string _searchString = searchString;
            string _category = category;
            string currentCategory = "";

            if (!String.IsNullOrEmpty(_searchString))
            {
                ViewBag.Title = "Results on your request";
                ViewBag.ResultSearch = "Results on your request:";
                monitors = monitors.Where(s => s.Name.ToLower().Contains(searchString.Trim().ToLower()));
                if (monitors.Count() == 0)
                {
                    ViewBag.NotFoundResultSearch = "Products not found! Try changing the query or choose from the following products:";
                    monitors = AllMonitors.Monitors.OrderBy(i => i.IsFavourite);
                }
            }
            if(!String.IsNullOrEmpty(_category))
            {
                if (string.Equals("touchscreen", category, StringComparison.OrdinalIgnoreCase))
                {
                    monitors = AllMonitors.Monitors.Where(i => i.Category.CategoryName.Equals("Touchscreen")).OrderBy(i => i.Id);
                    currentCategory = "Touchscreen";
                    ViewBag.Title = "Touchscreen";
                }
                else if (string.Equals("desktop", category, StringComparison.OrdinalIgnoreCase))
                {
                    monitors = AllMonitors.Monitors.Where(i => i.Category.CategoryName.Equals("Desktop")).OrderBy(i => i.Id);
                    currentCategory = "Desktop monitors";
                    ViewBag.Title = "Desktop monitors";
                }
                else if (string.Equals("lfd", category, StringComparison.OrdinalIgnoreCase))
                {
                    monitors = AllMonitors.Monitors.Where(i => i.Category.CategoryName.Equals("LFD")).OrderBy(i => i.Id);
                    currentCategory = "LFD monitors";
                    ViewBag.Title = "LFD monitors";
                }
                else if (string.Equals("gaming", category, StringComparison.OrdinalIgnoreCase))
                {
                    monitors = AllMonitors.Monitors.Where(i => i.Category.CategoryName.Equals("Gaming")).OrderBy(i => i.Id);
                    currentCategory = "Gaming monitors";
                    ViewBag.Title = "Gaming monitors";
                }
            }

            var monitorObj = new MonitorsListViewModel
            {
                AllMonitors = monitors,
                CurrentCategory = currentCategory,
                Categories = categoryList,
                DiagonalFilters = filterListDiagonal,
                ColorFilters = filterListColor                              
            }; 

            return View(monitorObj);
        }

        [HttpPost]        
        public IActionResult List(MonitorsListViewModel objFilterCat)            
        {            
            IEnumerable<Monitor> monitors = AllMonitors.Monitors;                     

            if (objFilterCat.Categories != null)
            {
                for (var i = 0; i < objFilterCat.Categories.Count(); i++)
                {
                    if (objFilterCat.Categories[i].CheckboxAnswer == true)
                    {
                        var allCheckCategoryMonitors = AllMonitors.Monitors.Where(t => t.Category.CategoryName == objFilterCat.Categories[i].CategoryName);                        
                        CheckingEmptyList(allCheckCategoryMonitors);
                        foreach (var item in allCheckCategoryMonitors)
                            tempListCategory.Add(item);
                    }
                }
            }            

            if (objFilterCat.DiagonalFilters != null)
            {
                for (var j = 0; j < objFilterCat.DiagonalFilters.Count; j++)
                {
                    if (objFilterCat.DiagonalFilters[j].CheckboxAnswer == true)
                    {
                        if (objFilterCat.DiagonalFilters[j].FilterDiagonal.Contains("small"))
                        {
                            var allCheckDiagonalMonitors = AllMonitors.Monitors.TakeWhile(t => t.Diagonal <= 15);
                            CheckingEmptyList(allCheckDiagonalMonitors);
                            AddCheckDiagonalItem(allCheckDiagonalMonitors);
                        }
                        else if (objFilterCat.DiagonalFilters[j].FilterDiagonal.Contains("middle"))
                        {
                            var allCheckDiagonalMonitors = AllMonitors.Monitors.SkipWhile(t => t.Diagonal < 15.1).TakeWhile(t => t.Diagonal <= 30);
                            CheckingEmptyList(allCheckDiagonalMonitors);
                            AddCheckDiagonalItem(allCheckDiagonalMonitors);
                        }
                        else if (objFilterCat.DiagonalFilters[j].FilterDiagonal.Contains("large"))
                        {
                            var allCheckDiagonalMonitors = AllMonitors.Monitors.SkipWhile(t => t.Diagonal < 30.1).TakeWhile(t => t.Diagonal <= 50);
                            CheckingEmptyList(allCheckDiagonalMonitors);
                            AddCheckDiagonalItem(allCheckDiagonalMonitors);                            
                        }
                        else if (objFilterCat.DiagonalFilters[j].FilterDiagonal.Contains("huge"))
                        {
                            var allCheckDiagonalMonitors = AllMonitors.Monitors.SkipWhile(t => t.Diagonal < 50.1);
                            CheckingEmptyList(allCheckDiagonalMonitors);
                            AddCheckDiagonalItem(allCheckDiagonalMonitors);
                        }                        
                    }
                }
            }            

            if (objFilterCat.ColorFilters != null)
            {
                for (var k = 0; k < objFilterCat.ColorFilters.Count; k++)
                {
                    if (objFilterCat.ColorFilters[k].CheckboxAnswer == true)
                    {
                        if (objFilterCat.ColorFilters[k].FilterColor.Contains("White"))
                        {
                            var allCheckColorMonitors = AllMonitors.Monitors.Where(t => t.Color.ToLower() == "white");
                            CheckingEmptyList(allCheckColorMonitors);                            
                            foreach (var item in allCheckColorMonitors)
                                tempListColor.Add(item);
                        }
                        if (objFilterCat.ColorFilters[k].FilterColor.Contains("Black"))
                        {
                            var allCheckColorMonitors = AllMonitors.Monitors.Where(t => t.Color.ToLower() == "black");
                            CheckingEmptyList(allCheckColorMonitors);                            
                            foreach (var item in allCheckColorMonitors)
                                tempListColor.Add(item);
                        }
                    }
                }
            }

            monitors = FormationListMatchingItems(monitors);

            if (checkedEmptyList > 0 || monitors.Count() == 0)
            {                
                monitors = new List<Monitor>();
                ViewBag.ResultFilters = "There are no products matching your selection. Сhange your filter options.";
            }

            if (monitors != null)
            {
                string selectValue = objFilterCat.Dropdown.Value;

                if (string.IsNullOrEmpty(selectValue))
                    selectValue = "IsFavourite";

                bool descending = false;
                if (selectValue.EndsWith("_desc"))
                {
                    selectValue = selectValue.Substring(0, selectValue.Length - 5);
                    descending = true;
                }

                if (descending)
                    monitors = monitors.AsQueryable().OrderBy(selectValue + " desc").ToList();
                else
                    monitors = monitors.AsQueryable().OrderBy(selectValue + " asc").ToList();
            }            

            var monitorObj = new MonitorsListViewModel
            {
                AllMonitors = monitors,
                Categories = objFilterCat.Categories,
                DiagonalFilters = objFilterCat.DiagonalFilters,
                ColorFilters = objFilterCat.ColorFilters,
                Dropdown = objFilterCat.Dropdown,
            };            

            return View(monitorObj);

Controllers/ShopCartController.cs
using EMarket.Data.Interfaces;
using EMarket.Data.Models;
using EMarket.ViewModel;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;

namespace EMarket.Controllers
{
    public class ShopCartController : Controller
    {
        private readonly IAllMonitors MonitorRep;
        private readonly IAllShopCarts ShopCartRep;        

        public ShopCartController(IAllMonitors monitorRep, IAllShopCarts shopCartRep)
        {
            MonitorRep = monitorRep;
            ShopCartRep = shopCartRep;            
        }

        public ViewResult Index()
        {
            List<ShopCartItem> items = ShopCartRep.ListShopCartItems;
            var price = ShopCartRep.TotalValueCalculation();
            
            ViewBag.Title = "Shop cart";
            var obj = new ShopCartViewModel { ShopCartItems = items, CartTotal = price };
            return View(obj);
        }

        public RedirectToActionResult AddCart(int id, int amount)
        {            
            var monitor = MonitorRep.Monitors.FirstOrDefault(x => x.Id == id);            
            if (monitor != null)
            {                
                ShopCartRep.AddToCart(monitor, 1);
            }

            List<ShopCartItem> items = ShopCartRep.ListShopCartItems;            
            return RedirectToAction("Index");
        }

        public RedirectToActionResult RemoveFromCart(int id)
        {
            var monitor = MonitorRep.Monitors.FirstOrDefault(x => x.Id == id);
            if(monitor != null)
            {                
                ShopCartRep.RemoveItem(monitor);
            }            

            return RedirectToAction("Index");            
        }

        public RedirectToActionResult ClearCart()
        {
            ShopCartRep.ClearShopcart();            
            return RedirectToAction("Index");
        }
    }
}

Views/Shared/AllMonitors.cshtml
@model Monitor

<div class="product-info cat-12" style="display:block;">
    <a asp-controller="DetailsMonitor" asp-action="OpenInfo" asp-route-id="@Model.Id">
        <span class="content-image">
            <img class="img" src="@Model.Img" alt="@Model.Name" width="166" height="140" border="0" style="opacity:1; z-index:0;" />
        </span>
        <span class="short">@Model.ShortDesc</span>
        <span class="name">@Model.Name</span>
        <span class="price">@Model.Price.ToString("c")</span>
    </a>
    <span><a class="btn btn-primary custom-btn-primary" asp-controller="ShopCart" asp-action="AddCart" asp-route-id="@Model.Id">Add to cart</a></span>
    <span><a class="btn btn-primary custom-btn-primary" asp-controller="DetailsMonitor" asp-action="OpenInfo" asp-route-id="@Model.Id">More info</a></span>    
</div>

Views/Shared/FavMonitor.cshtml
@model Monitor

<div class="fav-info cat-12" style="display:block;">
    <a asp-controller="DetailsMonitor" asp-action="OpenInfo" asp-route-id="@Model.Id">
        <span class="fav-image">
            <img class="fav-img" src="@Model.Img" alt="@Model.Name" />
        </span>
        <span class="fav-short">@Model.ShortDesc</span>
        <span class="fav-name">@Model.Name</span>
        <span class="fav-price">@Model.Price.ToString("c")</span>
    </a>     
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
    <head>
        <meta name="viewport" content="width=device-width" />
        <title>@ViewBag.Title</title>
        <link rel="icon" type="image/x-icon" href="~/img/ico/favicon.ico">
        <link href="~/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
        <link href="~/css/bootstrap-theme.css" rel="stylesheet" type="text/css"/>
        <link href="~/css/GlobalStyles.css" rel="stylesheet" type="text/css"/>
        <link href="~/css/LayoutStyles.css" rel="stylesheet" type="text/css"/> 
        <link href="~/css/HomePageStyles.css" rel="stylesheet" type="text/css"/> 
        <link href="~/css/AdminPanelPageStyles.css" rel="stylesheet" type="text/css"/>                
        <link href="~/css/PageListMonitorsStyles.css" rel="stylesheet" type="text/css"/> 
        <link href="~/css/PageSingleMonitorStyles.css" rel="stylesheet" type="text/css"/> 
        <link href="~/css/ShopCartStyles.css" rel="stylesheet" type="text/css"/> 
        <link href="~/css/SupportPageStyles.css" rel="stylesheet" type="text/css"/>
        <link href="~/css/PressPageStyles.css" rel="stylesheet" type="text/css"/>
        <link href="~/css/PrivacyPolicyPageStyles.css" rel="stylesheet" type="text/css"/>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>        
        <script src="https://code.jquery.com/jquery-latest.min.js"></script>        
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>        
        <script>
            $('.dropdown-toggle').click(function(e) {
                if ($(document).width() > 768) {
                    e.preventDefault();
                    var url = $(this).attr('href'); 
                    if (url !== '#') { 
                        window.location.href = url;
                    }
                }
            });
        </script>
        <script type="text/javascript">
            function toggle_show(id) {
                document.getElementById(id).style.display = document.getElementById(id).style.display == 'none' ? 'block' : 'none';
            }
        </script>
    </head>
<body>    
    <nav class="navbar navbar-expand-md navbar-dark bg-dark sticky-top"> 
        <div class="container-fluid">
            <a class="navbar-brand" asp-controller="Home" asp-action="Index" asp-route-area="">
                <img src=~/img/ico/logo-iiyama.png alt="iiyama">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav">
                    <li class="nav-item dropdown">
                        <a class="nav-link" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Products</a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" href="/Monitors/List/">All monitors</a>
                            <a class="dropdown-item" href="/Monitors/List/touchscreen">Touchscreen</a>
                            <a class="dropdown-item" href="/Monitors/List/desktop">Desktop</a>
                            <a class="dropdown-item" href="/Monitors/List/lfd">LFD</a>
                            <a class="dropdown-item" href="/Monitors/List/gaming">Gaming</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Support</a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" href="/Home/support/#warrantyf">Standard Warranty</a>
                            <a class="dropdown-item" href="/Home/support/#customer-servicef">Customer Service</a>
                            <a class="dropdown-item" href="/Home/support/#downloadsf">Downloads</a>                            
                            <a class="dropdown-item" href="/Home/support/#recyclingf">Recycling</a>
                            <a class="dropdown-item" href="/Home/support/#faqf">F.A.Q</a>                                                   
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Buy</a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" asp-controller="ShopCart" asp-action="Index" asp-route-area="">Shop cart</a>
                        </div>
                    </li>
                </ul>
                <form asp-controller="Monitors" asp-action="List" method="get" class="d-flex search-form-box">
                    <input class="form-control me-2" type="search" placeholder="Search" name="searchString" aria-label="Search">
                    <button class="btn btn-outline-primary custom-btn-outline-primary" type="submit">Search</button>
                </form>                
            </div>
        </div>
    </nav>      
    <main>
        <div class="nopadding">
            @if (TempData["message"] != null)
            {
                <div class="alert alert-success">@TempData["message"]</div>
            }
            @RenderBody()
        </div>
    </main>
    <div class="container-fluid bg-footer">
        <div class="container mt-40">
            <footer>
                <div class="row-f">
                    <div class="col-md-12 mt-4">
                        <div class="row footer-nav">
                            <div class="col-md-2 offset-md-1">
                                <ul>
                                    <li class="mb-4" style="font-size:18px;">COMPANY</li>
                                    <li>
                                        <a href="/Home/company/#profilef">Profile</a>
                                    </li>
                                    <li>
                                        <a href="/Home/privacy">Privacy policy</a>
                                    </li>
                                    <li>
                                        <a href="/Home/company/#lagalf">Legal notice</a>
                                    </li>
                                </ul>
                            </div>
                            <div class="col-md-2 offset-md-1">
                                <ul>
                                    <li class="mb-4" style="font-size:18px;">SHORTCUTS</li>
                                    <li>
                                        <a href="/Home/press/#pressf">Press material</a>
                                    </li>                       
                                </ul>
                            </div>
                            <div class="col-md-2 offset-md-1">
                                <ul>
                                    <li class="mb-4" style="font-size:18px;">USEFUL LINKS</li>
                                    <li>
                                        <a href="/Home/support/#windows8_10f">Windows 8/10 and iiyama monitors</a>
                                    </li>
                                    <li>
                                        <a href="/Home/support/#downloadsf">Downloads</a>
                                    </li>
                                </ul>
                            </div>
                            <div class="col-md-3 align-self-end">
                                <p style="font-size:13px;"> Copyright ©2022 iiyama Corporation</p>
                            </div>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>    
</body>
</html>