Areas/Admin/Controllers/ManagementController.cs
using EMarket.Data.Interfaces;
using EMarket.Data.Models;
using EMarket.ViewModel;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Linq.Dynamic.Core;

namespace EMarket.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ManagementController : Controller
    {
        private readonly IAllMonitors AllMonitors;
        private readonly IMonitorsCategory MonitorsCategory;

        public ManagementController(IAllMonitors allMonitors, IMonitorsCategory monitorsCategory)
        {
            AllMonitors = allMonitors;
            MonitorsCategory = monitorsCategory;
        }
                
        public IActionResult Index(
            string sortOrder,
            string currentFilter,
            string searchString,
            int? pageNumber)
        {
            ViewData["CurrentSort"] = sortOrder;
            ViewData["IdSortParm"] =
                String.IsNullOrEmpty(sortOrder) ? "Id_desc" : "";
            ViewData["CategoryIdSortParm"] =
                sortOrder == "CategoryId" ? "CategoryId_desc" : "CategoryId";
            ViewData["CategorySortParm"] =
                sortOrder == "Category" ? "Category_desc" : "Category";
            ViewData["NameSortParm"] =
                sortOrder == "Name" ? "Name_desc" : "Name";
            ViewData["DiagonalSortParm"] =
                sortOrder == "Diagonal" ? "Diagonal_desc" : "Diagonal";
            ViewData["PriceSortParm"] =
                sortOrder == "Price" ? "Price_desc" : "Price";
            ViewData["ColorSortParm"] =
                sortOrder == "Color" ? "Color_desc" : "Color";

            if (searchString != null)            
                pageNumber = 1;            
            else            
                searchString = currentFilter;            

            ViewData["CurrentFilter"] = searchString;

            IEnumerable<Monitor> monitors = AllMonitors.Monitors;

            if (!String.IsNullOrEmpty(searchString))            
                monitors = monitors.Where(s => s.Name.ToLower().Contains(searchString.Trim().ToLower()));            

            if (string.IsNullOrEmpty(sortOrder))            
                sortOrder = "Id";
            
            bool descending = false;
            if (sortOrder.EndsWith("_desc"))
            {
                sortOrder = sortOrder.Substring(0, sortOrder.Length - 5);
                descending = true;
            }

            if (descending)            
                monitors = monitors.AsQueryable().OrderBy(sortOrder + " desc").ToList();            
            else            
                monitors = monitors.AsQueryable().OrderBy(sortOrder + " asc").ToList();            

            int pageSize = 3;
            return View(PaginatedList<Monitor>.Create(monitors,
                pageNumber ?? 1, pageSize));
        }

        public IActionResult Details(int id)
        {
            var monitor = AllMonitors.GetObjectMonitor(id);
            int catId = monitor.CategoryId;
            Category currentCategory = MonitorsCategory.GetCategory(catId);

            if (monitor == null)            
                return NotFound();            

            var monitorObj = new DetailsMonitorViewModel
            {
                DetailsMonitor = monitor,
                Category = currentCategory,
            };

            return View(monitorObj);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(
            [Bind("Id, CategoryId, Category, Name, Diagonal, ShortDesc, LongDesc, Color, Img, Price, IsFavourite, Avalible")] Monitor monitor)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    AllMonitors.Create(monitor);
                    AllMonitors.Save();
                    TempData["message"] = string.Format("Product \"{0}\" was been created",
                    monitor.Name);
                    return RedirectToAction("Index");
                }
            }
            catch (DataException ex)
            {
                ModelState.AddModelError("", "Unable to save changes. Try again, and if the " +
                    "problem persists see your system administrator.");
            }

            return View(monitor);
        }

        public IActionResult Edit(int id)
        {
            var monitor = AllMonitors.GetObjectMonitor(id);
            int catId = monitor.CategoryId;
            Category currentCategory = MonitorsCategory.GetCategory(catId);

            if (monitor == null)            
                return NotFound();            

            return View(monitor);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id,
            [Bind("Id, CategoryId, Category, Name, Diagonal, ShortDesc, LongDesc, Color, Img, Price, IsFavourite, Avalible")] Monitor monitor)
        {

            if (id != monitor.Id)
                return NotFound();            

            if (ModelState.IsValid)
            {
                try
                {
                    AllMonitors.Update(monitor);                    
                    AllMonitors.Save();                    
                }
                catch (DataException ex)
                {
                    if (!AllMonitors.MonitorExists(monitor.Id))                    
                        return NotFound();                    
                    else                    
                        throw;                    
                }
                TempData["message"] = string.Format("Changes for product \"{0}\" was been saved", monitor.Name);
                return RedirectToAction("Index");
            }
            return View(monitor);
        }

        public IActionResult Delete(int id)
        {
            var monitor = AllMonitors.GetObjectMonitor(id);
            int catId = monitor.CategoryId;
            Category currentCategory = MonitorsCategory.GetCategory(catId);

            if (monitor == null)            
                return NotFound();            

            return View(monitor);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            var monitor = AllMonitors.GetObjectMonitor(id);
            AllMonitors.Delete(id);
            AllMonitors.Save();

            TempData["message"] = string.Format("Product \"{0}\" was been deleted",
                    monitor.Name);
            return RedirectToAction(nameof(Index));
        }

        //protected override void Dispose(bool disposing)
        //{
        //    AllMonitors.Monitors.Dispose();
        //    base.Dispose(disposing);
        //}
    }
}

Areas/Admin/Views/Management/Create.cshtml
@model Monitor

@{
    ViewData["Title"] = "Create";
}
<div class="add-product">
    <h1 style="text-align:center;">Create new product</h1>
    <h4 style="margin-left:30px;">Product data:</h4>
    <hr />
    <div class="row" style="margin-left:30px;">
        <div class="col-md-4">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="CategoryId" class="control-label"></label>
                    <input asp-for="CategoryId" class="form-control" />
                    <span asp-validation-for="CategoryId" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Category" class="control-label"></label>
                    <input asp-for="Category" class="form-control" />
                    <span asp-validation-for="Category" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
			    <div class="form-group">
                    <label asp-for="Diagonal" class="control-label"></label>
                    <input asp-for="Diagonal" class="form-control" />
                    <span asp-validation-for="Diagonal" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ShortDesc" class="control-label"></label>
                    <input asp-for="ShortDesc" class="form-control" />
                    <span asp-validation-for="ShortDesc" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="LongDesc" class="control-label"></label>
                    <input asp-for="LongDesc" class="form-control" />
                    <span asp-validation-for="LongDesc" class="text-danger"></span>
                </div>
			    <div class="form-group">
                    <label asp-for="Img" class="control-label"></label>
                    <input asp-for="Img" class="form-control" />
                    <span asp-validation-for="Img" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Price" class="control-label"></label>
                    <input asp-for="Price" class="form-control" />
                    <span asp-validation-for="Price" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Color" class="control-label"></label>
                    <input asp-for="Color" class="form-control" />
                    <span asp-validation-for="Color" class="text-danger"></span>
                </div><br />                
                <div class="form-group">
                    <label asp-for="IsFavourite" class="control-label"></label>
                    @Html.CheckBoxFor(model => model.IsFavourite)                    
                    <span asp-validation-for="IsFavourite" class="text-danger"></span>
                </div><br />
			    <div class="form-group">
                    <label asp-for="Avalible" class="control-label"></label> 
                    @Html.CheckBoxFor(model => model.Avalible)                    
                    <span asp-validation-for="Avalible" class="text-danger"></span>
                </div><br />            
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                    <a asp-area="Admin" asp-controller="Management" asp-action="Index" class="btn btn-primary">Back to List</a>
                </div>
            </form>
        </div>
    </div>
</div>

Areas/Admin/Views/Management/Delete.cshtml
@model Monitor

@{
    ViewData["Title"] = "Delete";
}
<div class="delete-product-box">
    <h1 style="text-align:center;">Delete product from database</h1>
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>Product:</h4>
        <hr />
        <dl class="row">
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.Id)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.Id)
            </dd>
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.CategoryId)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.CategoryId)
            </dd>
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.Category.CategoryName)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.Category.CategoryName)
            </dd>
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.Name)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.Name)
            </dd>
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.Diagonal)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.Diagonal)
            </dd>
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.ShortDesc)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.ShortDesc)
            </dd>
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.LongDesc)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.LongDesc)
            </dd>
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.Img)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.Img)
            </dd>
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.Price)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.Price)
            </dd>
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.Color)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.Color)
            </dd>
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.IsFavourite)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.IsFavourite)
            </dd>
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.Avalible)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.Avalible)
            </dd>        
        </dl>
    
        <form asp-area="Admin" asp-controller="Management" asp-action="Delete">
            <input type="hidden" asp-for="Id" />
            <input type="submit" value="Delete" class="btn btn-danger" /> 
            <a asp-area="Admin" asp-controller="Management" asp-action="Index" class="btn btn-primary">Back to List</a>
        </form>
    </div>
</div>

Areas/Admin/Views/Management/Details.cshtml
@model DetailsMonitorViewModel

<div class="details-product-box">
    <div class="col-sm-2">
        <h4 style="text-align:center;">@Html.DisplayFor(modelItem => modelItem.DetailsMonitor.Name)</h4>
    </div>
    <div class="col-md-12 details-table-wrap">
        <table class="table details-table">
            <tr>
                <th>MonitorID</th>
                <th>CategoryID</th>
                <th>Category</th>
                <th>Name</th>
                <th>Diagonal</th>            
                <th>Short description</th>
                <th>Long description</th>
                <th>Img</th>
                <th>Price</th>
                <th>Color</th>
                <th>Favourite</th>
                <th>Avalible</th>
            </tr>
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => modelItem.DetailsMonitor.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => modelItem.DetailsMonitor.CategoryId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => modelItem.Category.CategoryName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => modelItem.DetailsMonitor.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => modelItem.DetailsMonitor.Diagonal)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => modelItem.DetailsMonitor.ShortDesc)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => modelItem.DetailsMonitor.LongDesc)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => modelItem.DetailsMonitor.Img)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => modelItem.DetailsMonitor.Price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => modelItem.DetailsMonitor.Color)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => modelItem.DetailsMonitor.IsFavourite)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => modelItem.DetailsMonitor.Avalible)
                </td>
            </tr>
        </table>
    </div>    
    <div class="details-buttons">
        <div>
            <a asp-area="Admin" asp-controller="Management" asp-action="Edit" asp-route-id="@Model.DetailsMonitor.Id" class="btn btn-primary">Edit</a>
            <a asp-area="Admin" asp-controller="Management" asp-action="Delete" asp-route-id="@Model.DetailsMonitor.Id" class="btn btn-primary">Delete</a>
            <a asp-area="Admin" asp-controller="Management" asp-action="Index" class="btn btn-primary">Back to List</a>
        </div>
    </div>    
</div>

Areas/Admin/Views/Management/Edit.cshtml
@model Monitor

@{
    ViewData["Title"] = "Edit";
}

<div class="edit-product-box">
    <h1 style="text-align:center;">Edit product</h1>
    <h4 style="margin-left:30px;">Product</h4>
    <hr />
    <div class="row" style="margin-left:30px;">
        <div class="col-md-4">
            <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="Id" />
                 <div class="form-group">
                    <label asp-for="CategoryId" class="control-label"></label>
                    <input asp-for="CategoryId" class="form-control" />
                    <span asp-validation-for="CategoryId" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Category.CategoryName" class="control-label"></label>
                    <input asp-for="Category.CategoryName" class="form-control" />
                    <span asp-validation-for="Category.CategoryName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
			    <div class="form-group">
                    <label asp-for="Diagonal" class="control-label"></label>
                    <input asp-for="Diagonal" class="form-control" />
                    <span asp-validation-for="Diagonal" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ShortDesc" class="control-label"></label>
                    <input asp-for="ShortDesc" class="form-control" />
                    <span asp-validation-for="ShortDesc" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="LongDesc" class="control-label"></label>
                    <input asp-for="LongDesc" class="form-control" />
                    <span asp-validation-for="LongDesc" class="text-danger"></span>
                </div>
			    <div class="form-group">
                    <label asp-for="Img" class="control-label"></label>
                    <input asp-for="Img" class="form-control" />
                    <span asp-validation-for="Img" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Price" class="control-label"></label>
                    <input asp-for="Price" class="form-control" />
                    <span asp-validation-for="Price" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Color" class="control-label"></label>
                    <input asp-for="Color" class="form-control" />
                    <span asp-validation-for="Color" class="text-danger"></span>
                </div><br />
                <div class="form-group">
                    <label asp-for="IsFavourite" class="control-label"></label>
                    @Html.CheckBoxFor(model => model.IsFavourite)                              
                    <span asp-validation-for="IsFavourite" class="text-danger"></span>
                </div><br />
			    <div class="form-group">
                    <label asp-for="Avalible" class="control-label"></label>   
                    @Html.CheckBoxFor(model => model.Avalible)                     
                     <span asp-validation-for="Avalible" class="text-danger"></span>
                </div><br />
                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-primary" />
                    <a asp-area="Admin" asp-controller="Management" asp-action="Index" class="btn btn-primary">Back to List</a>
                </div>
            </form>
        </div>
    </div>
</div>

Areas/Admin/Views/Management/Index.cshtml
@model EMarket.PaginatedList<EMarket.Data.Models.Monitor>

@{
    ViewData["Title"] = "Index";
}
<div class="database-box">
    <h2 style="text-align:center;">Product database</h2>
    <p style="padding-left:20px;">
        <a asp-area="Admin" asp-controller="Management" asp-action="Create" class="btn btn-primary">Add new product</a>
        <a asp-area="Admin" asp-controller="Home" asp-action="AdminIndex" class="btn btn-primary">Back to panel menu</a>
    </p>
    <form asp-area="Admin" asp-controller="Management" asp-action="Index" method="get" style="padding-left:20px;">
        <div class="form-actions no-color">
            <p>
                Find by name: <input type="text" name="SearchString" value="@ViewData["CurrentFilter"]" />
                <input type="submit" value="Search" class="btn btn-default" /> |
                <a asp-area="Admin" asp-controller="Management" asp-action="Index">Back to Full List</a>
            </p>
        </div>
    </form>
    @{
        var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
        var nextDisabled = !Model.HasNextPage ? "disabled" : "";
    }
    <div>
        <a asp-area="Admin" asp-controller="Management" asp-action="Index"
           asp-route-sortOrder="@ViewData["CurrentSort"]"
           asp-route-pageNumber="@(Model.PageIndex - 1)"
           asp-route-currentFilter="@ViewData["CurrentFilter"]"
           class="btn btn-default @prevDisabled">
            Previous
        </a>
        <a asp-area="Admin" asp-controller="Management" asp-action="Index"
           asp-route-sortOrder="@ViewData["CurrentSort"]"
           asp-route-pageNumber="@(Model.PageIndex + 1)"
           asp-route-currentFilter="@ViewData["CurrentFilter"]"
           class="btn btn-default @nextDisabled">
            Next
        </a>
    </div>
    <div class="col-sm-12 database-table-wrap">
        <table class="table database-table" border="1" width="100%">
            <thead>
            <tr>
                <th><a asp-area="Admin" asp-controller="Management" asp-action="Index" asp-route-sortOrder="@ViewData["IdSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">ID</a></th>
                <th><a asp-area="Admin" asp-controller="Management" asp-action="Index" asp-route-sortOrder="@ViewData["CategoryIdSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Cate-<br />goryId</a></th>
                <th><a asp-area="Admin" asp-controller="Management" asp-action="Index" asp-route-sortOrder="@ViewData["CategorySortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Category</a></th>
                <th><a asp-area="Admin" asp-controller="Management" asp-action="Index" asp-route-sortOrder="@ViewData["NameSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Name</a></th>
                <th><a asp-area="Admin" asp-controller="Management" asp-action="Index" asp-route-sortOrder="@ViewData["DiagonalSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Diagonal</a></th>             
                <th><a asp-area="Admin" asp-controller="Management" asp-action="Index" asp-route-sortOrder="@ViewData["PriceSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Price</a></th>
                <th><a asp-area="Admin" asp-controller="Management" asp-action="Index" asp-route-sortOrder="@ViewData["ColorSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Color</a></th>
                <th>Favorite</th>
                <th>Avalible</th>
                <th>Short description</th>
                <th>Long description</th>
                <th>Img</th>
            </tr>
            </thead>
            <tbody>
                @foreach (var monitor in Model) {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelMonitor => monitor.Id)
                        </td>
                        <td>
                            @Html.DisplayFor(modelMonitor => monitor.CategoryId)
                        </td>
                        <td>
                            @Html.DisplayFor(modelMonitor => monitor.Category.CategoryName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelMonitor => monitor.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelMonitor => monitor.Diagonal)
                        </td>                   
                        <td>
                            @Html.DisplayFor(modelMonitor => monitor.Price)
                        </td>
                        <td>
                            @Html.DisplayFor(modelMonitor => monitor.Color)
                        </td>
                        <td>
                            @Html.DisplayFor(modelMonitor => monitor.IsFavourite)
                        </td>
                        <td>
                            @Html.DisplayFor(modelMonitor => monitor.Avalible)
                        </td>
                         <td>
                            @Html.DisplayFor(modelMonitor => monitor.ShortDesc)
                        </td>
                        <td>
                            @Html.DisplayFor(modelMonitor => monitor.LongDesc)
                        </td>
                        <td>
                            @Html.DisplayFor(modelMonitor => monitor.Img)
                        </td>
                    </tr>
                    <tr> 
                        <td colspan="11" style="text-align:left">
                        <a asp-area="Admin" asp-controller="Management" asp-action="Edit" asp-route-id="@monitor.Id" class="btn btn-primary">Edit</a>
                        <a asp-area="Admin" asp-controller="Management" asp-action="Details" asp-route-id="@monitor.Id" class="btn btn-primary">Details</a>
                        <a asp-area="Admin" asp-controller="Management" asp-action="Delete" asp-route-id="@monitor.Id" class="btn btn-danger">Delete</a>  
                        </td>
                    </tr>
                    }
            </tbody>
        </table>
    </div>  
    <div>
        <a asp-area="Admin" asp-controller="Management" asp-action="Index"
           asp-route-sortOrder="@ViewData["CurrentSort"]"
           asp-route-pageNumber="@(Model.PageIndex - 1)"
           asp-route-currentFilter="@ViewData["CurrentFilter"]"
           class="btn btn-default @prevDisabled">
            Previous
        </a>
        <a asp-area="Admin" asp-controller="Management" asp-action="Index"
           asp-route-sortOrder="@ViewData["CurrentSort"]"
           asp-route-pageNumber="@(Model.PageIndex + 1)"
           asp-route-currentFilter="@ViewData["CurrentFilter"]"
           class="btn btn-default @nextDisabled">
            Next
        </a>
    </div>
</div>